
# GET http://localhost:3000/composts/8

# GET https://compostons.herokuapp.com/composts

#  POST http://localhost:3000/composts 
#  content-type: application/json

#  {
#      "category": "Green",
#      "longitude": 1,
#      "latitude": 46
#  }

# DELETE http://localhost:3000/users/15



PUT http://localhost:3000/users/107/update
content-type: application/json

 {
    "category": "brown",
    "longitude": 2
}