# GET https://compostons.herokuapp.com/
POST http://localhost:4000/test
content-type: application/image/png

{
    "image": "https://m.media-amazon.com/images/I/71IcQqjPDiL._AC_SL1500_.jpg"
}

# DELETE http://localhost:4000/users/123/logout

#  GET http://localhost:4000/users

# POST https://compostons.herokuapp.com/register
# content-type: application/json

#  {
#     "username": "Michelaffghghhffff",
#     "mail": "michel.blanc@tfffhhgffgfhf.fr",
#     "password": "jaimelecompost",
#     "confirmedPassword": "jaimelecompost",
#     "role": "proposeur"
        
#  }

#  POST http://localhost:4000/users/174/mail
# content-type: application/json

#  {
#     "mail": "coucou c'est nous"
        
#  }

#  POST https://compostons.herokuapp.com/login
# content-type: application/json

#  {
#     "mail": "michel.blanc@yahoo.fr",
#     "password": "jaimelecompost"    
    
#  }

 

# GET https://compostons.herokuapp.com/composts

#  POST https://compostons.herokuapp.com/users/25
#  content-type: application/json

#  {
#      "category": "Green",
#      "longitude": "4"
    
#  }

# DELETE https://compostons.herokuapp.com/users/123/logout



# PUT https://compostons.herokuapp.com/users/
# content-type: application/json

#  {
#     "category": "Green"
    
# }


# PUT http://localhost:3000/users/100
# content-type: application/json

#  {
#     "lastname": "Test"
    
# }